apiVersion: apps/v1
kind: Deployment
metadata:
  name: owner-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: owner-service
  template:
    metadata:
      labels:
        app: owner-service
    spec:
      containers:
        - name: owner-service
          image: naveenalla/thewaiter-owner-service:1.0
          ports:
            - containerPort: 8081
          env:
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              value: "update"
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres-owner-service:5432/ownerdb
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: owner-service-secret
                  key: SPRING_DATASOURCE_USERNAME
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: owner-service-secret
                  key: SPRING_DATASOURCE_PASSWORD
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: owner-service-secret
                  key: JWT_SECRET
