apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-owner-statefulset
spec:
  serviceName: postgres-owner-service
  replicas: 1
  selector:
    matchLabels:
      app: postgres-owner
  template:
    metadata:
      labels:
        app: postgres-owner
    spec:
      containers:
        - name: postgres-owner-db-container
          image: postgres:14-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-owner-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-owner-secret
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              value: ownerdb
          volumeMounts:
            - name: postgres-owner-storage
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: postgres-owner-storage
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 5Gi
